### ISSUE TITLE
Syntax highlighting doesn't work as intended.

### ISSUE THREAD

**Issue by ghost** [andriusvelykis/reflow-maven-skin#11]
Looking at the resulting html in the highlight.js examples, the css class of the code blocks are based on the language name.

However, it appears that the doxia markdown conversion sets the class for all of these code blocks to "source".  

Syntax highlighting looks okay for simple languages such as xml, but when you try java, it's all wonky.

It's easy to reproduce:  Just update index.md of the reflow-skin site, add a code block in markdown with a hint of java.  The result won't match what is expected on the example site.

I'm looking through the velocity tools now to see if I can work around this by replacing the "source" selector as I see it, but I'm not sure that a) it's possible (still reading) and b) how to tell Velocity to use whatever I create to process the result (need to read more about velocity).

If you have ideas on how I can easily work around this, please let me know.

**Comment by ghost** [comment]
May be invalid after looking at the doxia sources.  Closing for now.

**Comment by ghost** [comment]
For reference in case anyone hits this: https://jira.codehaus.org/browse/DOXIA-488

**Comment by andriusvelykis** [comment]
Thanks for researching this. I did hope that the "automatic language detection" of  _highlight.js_ would help with the inability of explicitly indicating the language at the moment.

I guess we will just have to wait for the fix above.

**Comment by ghost** [comment]
Well, even with the fix, it doesn't work as one would think.

For example, if I set the highlight theme to solarized_dark, the 
background of the pre block doesn't match the example on the 
highlight.js themes page.

Based on some digging with FF's developer tools, it appeared that the 
css definitions from bootstrap were interfering.   Maybe something to 
investigate?

**Comment by cchantep** [comment]
Here is proposal for doxia md using jygments for highlighting: http://jira.codehaus.org/browse/DOXIA-507
