### ISSUE TITLE
XML in Markdown breaks plugin generation

### ISSUE THREAD

**Issue by roadtripryan** [andriusvelykis/reflow-maven-skin#14]
If I have a markdown document with some xml:

this is a test

```
  <project>
   ....
   </project>
```

The plugin errors:

line [3] Error parsing the model: end tag name </p> must match start tag name <project> from line 3 (position: TEXT seen ...<project> &hellip;.</p>... @3:79) -> [Help 1]

Any ideas for a work around? Our documentation has a lot of code samples in it... 

Thanks

**Comment by andriusvelykis** [comment]
Hmm, interestingly the [Reflow Maven Skin website](http://andriusvelykis.github.io/reflow-maven-skin/) itself embeds XML source code, e.g. the _Get it now_ section in the home page.

Could you produce a minimal example that reproduces your problem? In the website I am wrapping the XML content into fenced code blocks using ```. See the website source files, e.g. [index.md](https://raw.github.com/andriusvelykis/reflow-maven-skin/master/src/site/markdown/index.md).

**Comment by roadtripryan** [comment]
Ah, I didn't know you could wrap using fenced code blocks. I was just using 4+ space to denote a code block.  Using ``` worked perfectly. Thanks!

**Comment by andriusvelykis** [comment]
Indentation should have worked as well - it is standard Markdown :) maybe I will still have to check if indentation is causing problems..
