### ISSUE TITLE
Spurious </header> element

### ISSUE THREAD

**Issue by masih** [andriusvelykis/reflow-maven-skin#16]
In line [1554](https://github.com/andriusvelykis/reflow-maven-skin/blob/master/reflow-maven-skin/src/main/resources/META-INF/maven/site.vm#L1554) of site.vm the `</header>` tag seems out of place.
Should it not be at the end of line [1490](https://github.com/andriusvelykis/reflow-maven-skin/blob/master/reflow-maven-skin/src/main/resources/META-INF/maven/site.vm#L1490)?

Thanks

**Comment by andriusvelykis** [comment]
Thanks! Fixed this.

The `</header>` tag needed to be at the end to include breadcrumbs and toc within the `<header></header>`. Ensured now that opening `<header>` tag is printed even if banner is not displayed.
