### ISSUE TITLE
Image previews (lightbox) don't work anymore with 1.1.0

### ISSUE THREAD

**Issue by dadg** [andriusvelykis/reflow-maven-skin#35]
Hi,

It seems that the image preview (lightbox) don't work anymore with the 1.1.0 release.
Check on [your documentation](http://andriusvelykis.github.io/reflow-maven-skin/skin/misc.html#Image_previews_lightbox), the lightbox is started but no image displayed.

I got the same problem with my site. If I downgrade to 1.0.0 it's working fine.

WBR // David

**Comment by andriusvelykis** [comment]
Thanks - upgraded to the newest Lightbox2 version, it supports newer jQuery versions: lokesh/lightbox2#35. The jQuery upgrade in Reflow skin 1.1.0 (see #9) broke it..

Sorry for a long turnaround time!

**Comment by andriusvelykis** [comment]
Released Reflow skin v1.1.1 with the fix - it should sync to Maven Central soon.

**Comment by dadg** [comment]
Hi,

I give a try this morning with the 1.1.1 version.
It **works prefectly**. Great work, thanks you so much.

WBR // David
