### ISSUE TITLE
topNav items isn't generating

### ISSUE THREAD

**Issue by gtapper** [andriusvelykis/reflow-maven-skin#46]
Refer to the attached pom.xml and site.xml for configuration. (.xml changed to .txt to allow upload)

[pom.txt](https://github.com/andriusvelykis/reflow-maven-skin/files/31666/pom.txt)
[site.txt](https://github.com/andriusvelykis/reflow-maven-skin/files/31665/site.txt)

index.md is just a copy of the reflow index.md as a place holder.

For some reason, the topNav menu items are not generated. I'm staring myself blind on the site.xml file failing to figure out the issue.

**Comment by andriusvelykis** [comment]
Hi, sorry for the delay in replying. I have tried re-running it on my side and top navigation got generated successfully. Could you give more details on how you are running it?

**Comment by gtapper** [comment]
The issue seemed to have been related to the css file. I replaced it with the one used for reflow and now it works. Now, I'm trying to figure out how to change carousel settings in the site.css files; the default is too fast.
